# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 447)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("""
        QMainWindow {
                background-color: #E3F2FD; /* Azul suave */
        }

        QLabel {
                font-family: 'Segoe UI', Arial;
                color: #333;
        }

        QLineEdit {
                background-color: #FFFFFF;
                border: 2px solid #90CAF9;
                border-radius: 6px;
                padding: 6px;
                font-size: 14px;
        }
        QLineEdit:focus {
                border: 2px solid #42A5F5;
                background-color: #FAFAFA;
        }

        QPushButton {
                background-color: #42A5F5;
                color: white;
                border: none;
                border-radius: 6px;
                padding: 6px 14px;
                font-weight: bold;
                font-size: 14px;
        }
        QPushButton:hover {
                background-color: #1E88E5;
        }
        QPushButton:pressed {
                background-color: #1565C0;
        }

        QLabel#LocalInfo {
                background-color: #FFFFFF;
                border: 1px solid #AAAAAA;
                border-radius: 4px;
                padding: 4px;
                font-size: 14px;
        }

        QLabel#LocalInput {
                background-color: #FFFFFF;
                border: 1px solid #AAAAAA;
                border-radius: 4px;
                padding: 4px;
        }

        QLabel#LocalLabel {
                font-family: Segoe UI, Arial;
                font-size: 22px;
                color: #333;
        }


        QLabel[objectName^="day"] {
                background-color: #FFFFFF;
                border: 1px solid #B0BEC5;
                border-radius: 6px;
                padding: 6px;
                font-size: 13px;
                font-weight: bold;
                color: #37474F;
                qproperty-alignment: AlignCenter;
        }

        QLabel[objectName^="temperature"] {
                font-family: 'Calibri Light';
                font-size: 16px;
                font-weight: bold;
                color: #455A64;
                qproperty-alignment: AlignCenter;
        }

        QMenuBar {
                background-color: #90CAF9;
                color: white;
                font-weight: bold;
        }
        QMenuBar::item:selected {
                background-color: #42A5F5;
        }
        QMenu {
                background-color: #FFFFFF;
                border: 1px solid #B0BEC5;
        }
        QMenu::item:selected {
                background-color: #E3F2FD;
        }
        """)

        # widget principal
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")

        # grid layout
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")

        # etiqueta com a palavra local
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LocalLabel = QtWidgets.QLabel(self.centralwidget)
        self.LocalLabel.setObjectName("LocalLabel")
        self.horizontalLayout_2.addWidget(self.LocalLabel)

        # LineEdit que é responsavel por obter a input do local escolhido pelo user
        self.LocalInput = QtWidgets.QLineEdit(self.centralwidget)

        # botao que ao ser pressionado, significa que o user escolheu aquele local
        self.horizontalLayout_2.addWidget(self.LocalInput)
        self.LocalButton = QtWidgets.QPushButton(self.centralwidget)
        self.horizontalLayout_2.addWidget(self.LocalButton)

        # etiqueta com mais detalhes sobre o local que vao ser recebidos da api
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.LocalInfo = QtWidgets.QLabel(self.centralwidget)
        self.LocalInfo.setObjectName("LocalInfo")

        self.gridLayout_4.addWidget(self.LocalInfo, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(850, 290))
        self.groupBox.setSizeIncrement(QtCore.QSize(2000, 1200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")

        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")

        # layout horizontal onde vao estar os icones do tempo
        self.IconsLayout = QtWidgets.QHBoxLayout()
        self.IconsLayout.setObjectName("IconsLayout")
        self.icon1 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.icon1.sizePolicy().hasHeightForWidth())
        self.icon1.setSizePolicy(sizePolicy)
        self.icon1.setMinimumSize(QtCore.QSize(30, 50))
        self.icon1.setMaximumSize(QtCore.QSize(400, 300))
        self.icon1.setObjectName("icon1")
        self.IconsLayout.addWidget(self.icon1)
        self.icon2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.icon2.sizePolicy().hasHeightForWidth())
        self.icon2.setSizePolicy(sizePolicy)
        self.icon2.setMinimumSize(QtCore.QSize(30, 50))
        self.icon2.setMaximumSize(QtCore.QSize(400, 300))
        self.icon2.setObjectName("icon2")
        self.IconsLayout.addWidget(self.icon2)
        self.icon3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.icon3.sizePolicy().hasHeightForWidth())
        self.icon3.setSizePolicy(sizePolicy)
        self.icon3.setMinimumSize(QtCore.QSize(30, 50))
        self.icon3.setMaximumSize(QtCore.QSize(400, 300))
        self.icon3.setObjectName("icon3")
        self.IconsLayout.addWidget(self.icon3)
        self.icon4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.icon4.sizePolicy().hasHeightForWidth())
        self.icon4.setSizePolicy(sizePolicy)
        self.icon4.setMinimumSize(QtCore.QSize(30, 50))
        self.icon4.setMaximumSize(QtCore.QSize(400, 300))
        self.icon4.setObjectName("icon4")
        self.IconsLayout.addWidget(self.icon4)
        self.icon5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.icon5.sizePolicy().hasHeightForWidth())
        self.icon5.setSizePolicy(sizePolicy)
        self.icon5.setMinimumSize(QtCore.QSize(30, 50))
        self.icon5.setMaximumSize(QtCore.QSize(400, 300))
        self.icon5.setObjectName("icon5")
        self.IconsLayout.addWidget(self.icon5)
        self.icon6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.icon6.sizePolicy().hasHeightForWidth())
        self.icon6.setSizePolicy(sizePolicy)
        self.icon6.setMinimumSize(QtCore.QSize(30, 50))
        self.icon6.setMaximumSize(QtCore.QSize(400, 300))
        self.icon6.setObjectName("icon6")
        self.IconsLayout.addWidget(self.icon6)
        self.icon7 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.icon7.sizePolicy().hasHeightForWidth())
        self.icon7.setSizePolicy(sizePolicy)
        self.icon7.setMinimumSize(QtCore.QSize(30, 50))
        self.icon7.setMaximumSize(QtCore.QSize(400, 300))
        self.icon7.setObjectName("icon7")
        self.IconsLayout.addWidget(self.icon7)
        self.gridLayout_3.addLayout(self.IconsLayout, 2, 0, 1, 1)

        # layout horizontal onde vai estar a temperatura maxima e minima para cada dia
        self.TemperaturesLayout = QtWidgets.QHBoxLayout()
        self.TemperaturesLayout.setObjectName("TemperaturesLayout")
        self.temperature1 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.temperature1.sizePolicy().hasHeightForWidth())
        self.temperature1.setSizePolicy(sizePolicy)
        self.temperature1.setMinimumSize(QtCore.QSize(30, 50))
        self.temperature1.setMaximumSize(QtCore.QSize(400, 300))
        self.temperature1.setObjectName("temperature1")
        self.TemperaturesLayout.addWidget(self.temperature1)
        self.temperature2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.temperature2.sizePolicy().hasHeightForWidth())
        self.temperature2.setSizePolicy(sizePolicy)
        self.temperature2.setMinimumSize(QtCore.QSize(30, 50))
        self.temperature2.setMaximumSize(QtCore.QSize(400, 300))
        self.temperature2.setObjectName("temperature2")
        self.TemperaturesLayout.addWidget(self.temperature2)
        self.temperature3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.temperature3.sizePolicy().hasHeightForWidth())
        self.temperature3.setSizePolicy(sizePolicy)
        self.temperature3.setMinimumSize(QtCore.QSize(30, 50))
        self.temperature3.setMaximumSize(QtCore.QSize(400, 300))
        self.temperature3.setObjectName("temperature3")
        self.TemperaturesLayout.addWidget(self.temperature3)
        self.temperature4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.temperature4.sizePolicy().hasHeightForWidth())
        self.temperature4.setSizePolicy(sizePolicy)
        self.temperature4.setMinimumSize(QtCore.QSize(30, 50))
        self.temperature4.setMaximumSize(QtCore.QSize(400, 300))
        self.temperature4.setObjectName("temperature4")
        self.TemperaturesLayout.addWidget(self.temperature4)
        self.temperature5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.temperature5.sizePolicy().hasHeightForWidth())
        self.temperature5.setSizePolicy(sizePolicy)
        self.temperature5.setMinimumSize(QtCore.QSize(30, 50))
        self.temperature5.setMaximumSize(QtCore.QSize(400, 300))
        self.temperature5.setObjectName("temperature5")
        self.TemperaturesLayout.addWidget(self.temperature5)
        self.temperature6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.temperature6.sizePolicy().hasHeightForWidth())
        self.temperature6.setSizePolicy(sizePolicy)
        self.temperature6.setMinimumSize(QtCore.QSize(30, 50))
        self.temperature6.setMaximumSize(QtCore.QSize(400, 300))
        self.temperature6.setObjectName("temperature6")
        self.TemperaturesLayout.addWidget(self.temperature6)
        self.temperature7 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.temperature7.sizePolicy().hasHeightForWidth())
        self.temperature7.setSizePolicy(sizePolicy)
        self.temperature7.setMinimumSize(QtCore.QSize(30, 50))
        self.temperature7.setMaximumSize(QtCore.QSize(400, 300))
        self.temperature7.setObjectName("temperature7")
        self.TemperaturesLayout.addWidget(self.temperature7)
        self.gridLayout_3.addLayout(self.TemperaturesLayout, 3, 0, 1, 1)

        # layout horizontal onde vao estar os dias da semana
        self.Title = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.gridLayout_3.addWidget(self.Title, 0, 0, 1, 1)
        self.DaysLayout = QtWidgets.QHBoxLayout()
        self.DaysLayout.setObjectName("DaysLayout")
        self.day1 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.day1.sizePolicy().hasHeightForWidth())
        self.day1.setSizePolicy(sizePolicy)
        self.day1.setObjectName("day1")
        self.DaysLayout.addWidget(self.day1)
        self.day2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.day2.sizePolicy().hasHeightForWidth())
        self.day2.setSizePolicy(sizePolicy)
        self.day2.setObjectName("day2")
        self.DaysLayout.addWidget(self.day2)
        self.day3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.day3.sizePolicy().hasHeightForWidth())
        self.day3.setSizePolicy(sizePolicy)
        self.day3.setObjectName("day3")
        self.DaysLayout.addWidget(self.day3)
        self.day4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.day4.sizePolicy().hasHeightForWidth())
        self.day4.setSizePolicy(sizePolicy)
        self.day4.setObjectName("day4")
        self.DaysLayout.addWidget(self.day4)
        self.day5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.day5.sizePolicy().hasHeightForWidth())
        self.day5.setSizePolicy(sizePolicy)
        self.day5.setMinimumSize(QtCore.QSize(30, 50))
        self.day5.setMaximumSize(QtCore.QSize(400, 300))
        self.day5.setObjectName("day5")
        self.DaysLayout.addWidget(self.day5)
        self.day6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.day6.sizePolicy().hasHeightForWidth())
        self.day6.setSizePolicy(sizePolicy)
        self.day6.setObjectName("day6")
        self.DaysLayout.addWidget(self.day6)
        self.day7 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.day7.sizePolicy().hasHeightForWidth())
        self.day7.setSizePolicy(sizePolicy)
        self.day7.setObjectName("day7")
        self.DaysLayout.addWidget(self.day7)
        self.gridLayout_3.addLayout(self.DaysLayout, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 874, 27))
        self.menubar.setObjectName("menubar")
        self.menuClima = QtWidgets.QMenu(self.menubar)
        self.menuClima.setObjectName("menuClima")
        self.menuAcerca_de = QtWidgets.QMenu(self.menubar)
        self.menuAcerca_de.setObjectName("menuAcerca_de")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuClima.menuAction())
        self.menubar.addAction(self.menuAcerca_de.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LocalLabel.setText(_translate("MainWindow", "Local:"))
        self.LocalButton.setText(_translate("MainWindow", "Confirmar"))
        self.icon1.setText(_translate("MainWindow", ""))
        self.icon2.setText(_translate("MainWindow", ""))
        self.icon3.setText(_translate("MainWindow", ""))
        self.icon4.setText(_translate("MainWindow", ""))
        self.icon5.setText(_translate("MainWindow", ""))
        self.icon6.setText(_translate("MainWindow", ""))
        self.icon7.setText(_translate("MainWindow", ""))
        self.temperature1.setText(_translate("MainWindow", "32ºC 40ºC"))
        self.temperature2.setText(_translate("MainWindow", "22ºC 30ºC"))
        self.temperature3.setText(_translate("MainWindow", "18ºC 30ºC"))
        self.temperature4.setText(_translate("MainWindow", "10ºC 20ºC"))
        self.temperature5.setText(_translate("MainWindow", "30ºC 40ºC"))
        self.temperature6.setText(_translate("MainWindow", "12ºC 22ºC"))
        self.temperature7.setText(_translate("MainWindow", "30ºC 40ºC"))
        self.Title.setText(_translate("MainWindow", "Previsão do tempo para esta semana:"))
        self.day1.setText(_translate("MainWindow", "Segunda"))
        self.day2.setText(_translate("MainWindow", "Terça"))
        self.day3.setText(_translate("MainWindow", "Quarta"))
        self.day4.setText(_translate("MainWindow", "Quinta"))
        self.day5.setText(_translate("MainWindow", "Sexta"))
        self.day6.setText(_translate("MainWindow", "Sábado"))
        self.day7.setText(_translate("MainWindow", "Domingo"))
        self.menuClima.setTitle(_translate("MainWindow", "Clima"))
        self.menuAcerca_de.setTitle(_translate("MainWindow", "Acerca de"))
