# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# Import necessary modules from PyQt5
import PyQt5.QtGui
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *


# Define a class Ui_MainWindow that inherits from object
class Ui_MainWindow(object):
    # Method to set up the user interface
    def setupUi(self, MainWindow):
        # Check if MainWindow has an object name, and set it if not
        if not MainWindow.objectName():
            MainWindow.setObjectName("MainWindow")

        # Set the size of the main window
        MainWindow.resize(624, 725)

        # Create actions for the menu
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionHelp = QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp_2 = QAction(MainWindow)
        self.actionHelp_2.setObjectName("actionHelp_2")
        self.actionAbout_2 = QAction(MainWindow)
        self.actionAbout_2.setObjectName("actionAbout_2")

        # Create a central widget
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Create a grid layout for the central widget
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        # Create a button
        self.Button = QPushButton(self.centralwidget)
        self.Button.setObjectName("Button")

        # Add the button to the grid layout
        self.gridLayout.addWidget(self.Button, 3, 2, 1, 1)

        # Create a label
        self.Label = QLabel(self.centralwidget)
        self.Label.setObjectName("Label")

        # Set the font and properties of the label
        font = PyQt5.QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Label.setFont(font)
        self.Label.setLayoutDirection(Qt.LeftToRight)
        self.Label.setAutoFillBackground(True)
        self.Label.setTextFormat(Qt.AutoText)
        self.Label.setScaledContents(False)
        self.Label.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignTop)
        self.Label.setMargin(3)
        self.Label.setTextInteractionFlags(Qt.NoTextInteraction)

        # Add the label to the grid layout
        self.gridLayout.addWidget(self.Label, 0, 1, 1, 1)

        # Create a text edit field
        self.Text = QLineEdit(self.centralwidget)
        self.Text.setObjectName("Text")

        # Add the text edit field to the grid layout
        self.gridLayout.addWidget(self.Text, 3, 1, 1, 1)

        # Create a text box
        self.TextBox = QPlainTextEdit(self.centralwidget)
        self.TextBox.setObjectName("TextBox")

        # Add the text box to the grid layout
        self.gridLayout.addWidget(self.TextBox, 1, 1, 1, 2)

        # Set the central widget of the main window
        MainWindow.setCentralWidget(self.centralwidget)

        # Create a status bar
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Create a menu bar
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        self.menubar.setGeometry(QRect(0, 0, 624, 27))
        self.menuInfo = QMenu(self.menubar)
        MainWindow.setMenuBar(self.menubar)

        # Call the retranslateUi method to set up the UI translations
        self.retranslateUi(MainWindow)

        # Connect slots by name
        QMetaObject.connectSlotsByName(MainWindow)

    # Method to set up the UI translations
    def retranslateUi(self, MainWindow):
        # Set the window title
        MainWindow.setWindowTitle(
            QCoreApplication.translate("MainWindow", "Todo App", None)
        )

        # Set the text of the close action
        self.actionClose.setText(
            QCoreApplication.translate("MainWindow", "Close", None)
        )

        # Set the text of the button
        self.Button.setText(QCoreApplication.translate("MainWindow", "Submit", None))

        # Set the text of the label
        self.Label.setText(QCoreApplication.translate("MainWindow", "Todo List", None))
